### PR TITLE
Fix for issue 33

### LINKED ISSUE #33: Adopt new notebookWorkspaceEdit proposal
👋  We're currently working to finalize VS Code apis for editing notebooks. As part of this work, we've deprecated the `notebookEditorEdit` API proposal and have replaced it with a [new `notebookWorkspaceEdit` proposal](https://github.com/microsoft/vscode/blob/18cf3d01ed22f7b35895a9b3c531048c835d4489/src/vscode-dts/vscode.proposed.notebookWorkspaceEdit.d.ts#L13)

This proposal should offer the same functionality as the old API, but expresses it differently. 

However before finalizing this new API, we'd like to hear your feedback about it. Please try migrating to the new `notebookWorkspaceEdit` API and let me know if you run into any problems or have any concerns

If everything looks good with the `notebookWorkspaceEdit` proposal, please go ahead and check in the migration to the new API so we can eventually remove the old, now deprecated `notebookEditorEdit` proposal 

See https://github.com/microsoft/vscode/issues/149181 for details

### PR DESCRIPTION
**Pull request by rchiodo**
Fixes #33 

Use the new API proposal

### CODE REVIEW

File: src/notebookRunGroups/util/cellMetadataHelpers.ts [hunk 1]
```diff
@@ -26,6 +26,7 @@ export function updateCellRunGroupMetadata(cell: vscode.NotebookCell, newGroupVa
 
     // Perform our actual replace and edit
     const wsEdit = new vscode.WorkspaceEdit();
-    wsEdit.replaceNotebookCellMetadata(cell.notebook.uri, cell.index, newMetadata);
+    const notebookEdit = vscode.NotebookEdit.updateCellMetadata(cell.index, newMetadata);
```
Comment (IanMatthewHuff) [inline src/notebookRunGroups/util/cellMetadataHelpers.ts:29]: @rchiodo Thanks! You can always poke me for powertoy fixes as well. I don't mind fixing up mine at any time.
